# This file has been generated by node2nix 1.9.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "JSONStream-1.3.5" = {
      name = "JSONStream";
      packageName = "JSONStream";
      version = "1.3.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/JSONStream/-/JSONStream-1.3.5.tgz";
        sha512 = "E+iruNOY8VV9s4JEbe1aNEm6MiszPRr/UfcHMz0TQh1BXSxHK+ASV1R6W4HpjBhSeS+54PIsAMCBmwD06LLsqQ==";
      };
    };
    "acorn-7.1.1" = {
      name = "acorn";
      packageName = "acorn";
      version = "7.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/acorn/-/acorn-7.1.1.tgz";
        sha512 = "add7dgA5ppRPxCFJoAGfMDi7PIBXq1RtGo7BhbLaxwrXPOmw8gq48Y9ozT01hUKy9byMjlR20EJhu5zlkErEkg==";
      };
    };
    "acorn-node-1.8.2" = {
      name = "acorn-node";
      packageName = "acorn-node";
      version = "1.8.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/acorn-node/-/acorn-node-1.8.2.tgz";
        sha512 = "8mt+fslDufLYntIoPAaIMUe/lrbrehIiwmR3t2k9LljIzoigEPF27eLk2hy8zSGzmR/ogr7zbRKINMo1u0yh5A==";
      };
    };
    "acorn-walk-7.1.1" = {
      name = "acorn-walk";
      packageName = "acorn-walk";
      version = "7.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/acorn-walk/-/acorn-walk-7.1.1.tgz";
        sha512 = "wdlPY2tm/9XBr7QkKlq0WQVgiuGTX6YWPyRyBviSoScBuLfTVQhvwg6wJ369GJ/1nPfTLMfnrFIfjqVg6d+jQQ==";
      };
    };
    "admin-lte-2.4.18" = {
      name = "admin-lte";
      packageName = "admin-lte";
      version = "2.4.18";
      src = fetchurl {
        url = "https://registry.npmjs.org/admin-lte/-/admin-lte-2.4.18.tgz";
        sha512 = "AfIdoUWdbQA0OmW7PnP8GJ3u6RMKNXefN3DRTBHCQXd7VeyJahUfZWtV62ppDxcdjpx0L08ypPV55ARmdGdOIw==";
      };
    };
    "angular-1.6.10" = {
      name = "angular";
      packageName = "angular";
      version = "1.6.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/angular/-/angular-1.6.10.tgz";
        sha512 = "PCZ5/hVdvPQiYyH0VwsPjrErPHRcITnaXxhksceOXgtJeesKHLA7KDu4X/yvcAi+1zdGgGF+9pDxkJvghXI9Wg==";
      };
    };
    "angular-1.7.0" = {
      name = "angular";
      packageName = "angular";
      version = "1.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/angular/-/angular-1.7.0.tgz";
        sha512 = "3LboCLjrOuC7dWh953O0+dI3dJ7PexYRSCIrfqoN5qoHyja/wak3eWoxPKb2Sl2qwiPbrUV5KJXwgpUQ48McBQ==";
      };
    };
    "angular-1.8.2" = {
      name = "angular";
      packageName = "angular";
      version = "1.8.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/angular/-/angular-1.8.2.tgz";
        sha512 = "IauMOej2xEe7/7Ennahkbb5qd/HFADiNuLSESz9Q27inmi32zB0lnAsFeLEWcox3Gd1F6YhNd1CP7/9IukJ0Gw==";
      };
    };
    "angular-animate-1.6.10" = {
      name = "angular-animate";
      packageName = "angular-animate";
      version = "1.6.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/angular-animate/-/angular-animate-1.6.10.tgz";
        sha512 = "RU9ZJbTspq0W0x675H5k1DeSgKbAFfp2aiYoNGdlD+wQNKvwwMR5ho+EkDKkx9zE02a5goe8Z6EhhYPQSff9dA==";
      };
    };
    "angular-bittorrent-peerid-1.3.2" = {
      name = "angular-bittorrent-peerid";
      packageName = "angular-bittorrent-peerid";
      version = "1.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/angular-bittorrent-peerid/-/angular-bittorrent-peerid-1.3.2.tgz";
        sha512 = "oWLlaQA9SFVWPkLLPNwAN0n7E/b8jq/wEq9dalU247xNVg7KY2y9lOKFgvTnhyreajzqTjqwlfD7+Q+3/i9agg==";
      };
    };
    "angular-busy-4.1.4" = {
      name = "angular-busy";
      packageName = "angular-busy";
      version = "4.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/angular-busy/-/angular-busy-4.1.4.tgz";
        sha1 = "b4f1b333ec7ced31c207db5e3d77665375d18ea0";
      };
    };
    "angular-clipboard-1.7.0" = {
      name = "angular-clipboard";
      packageName = "angular-clipboard";
      version = "1.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/angular-clipboard/-/angular-clipboard-1.7.0.tgz";
        sha512 = "4/eg3zZw1MJpIsMc+mWzeVNyWBu8YWpXPTdmbgyPRp/6f0xB6I3XR2iC6Mb4mg/5E9q6exCd0sX2yiIsw+ZLJw==";
      };
    };
    "angular-cookies-1.6.10" = {
      name = "angular-cookies";
      packageName = "angular-cookies";
      version = "1.6.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/angular-cookies/-/angular-cookies-1.6.10.tgz";
        sha512 = "ADfbqXLhwcaecAiWIaxpl8XWFJgWsrDl/ksSEkYm5dSoXHYlj3HKlAhPbjBv/foYS7pdI0apmSGHWrBPqdjF/g==";
      };
    };
    "angular-input-dropdown-git://github.com/mayswind/angular-input-dropdown.git#68670e39816698b3eb98c0e740a0efe77d5fbdd1" = {
      name = "angular-input-dropdown";
      packageName = "angular-input-dropdown";
      version = "1.1.2";
      src = fetchgit {
        url = "git://github.com/mayswind/angular-input-dropdown.git";
        rev = "68670e39816698b3eb98c0e740a0efe77d5fbdd1";
        sha256 = "3e29aa14f217dbaa06fd1618067d1431c6f3cce0a722f3f1dbe3e845f98dc9de";
      };
    };
    "angular-local-storage-0.7.1" = {
      name = "angular-local-storage";
      packageName = "angular-local-storage";
      version = "0.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/angular-local-storage/-/angular-local-storage-0.7.1.tgz";
        sha1 = "fbd2730763c29fa9af5725e0186c780621e8cdd2";
      };
    };
    "angular-messages-1.6.10" = {
      name = "angular-messages";
      packageName = "angular-messages";
      version = "1.6.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/angular-messages/-/angular-messages-1.6.10.tgz";
        sha512 = "FpILIYqeBj2fP5U5txnO/cneeKZxdF+WqpBo7tgHXl2BmOVVWKUCEjMmByouYxwn9PFLeipBPjaaDs2/eB/m5A==";
      };
    };
    "angular-moment-1.3.0" = {
      name = "angular-moment";
      packageName = "angular-moment";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/angular-moment/-/angular-moment-1.3.0.tgz";
        sha512 = "KG8rvO9MoaBLwtGnxTeUveSyNtrL+RNgGl1zqWN36+HDCCVGk2DGWOzqKWB6o+eTTbO3Opn4hupWKIElc8XETA==";
      };
    };
    "angular-promise-buttons-0.1.23" = {
      name = "angular-promise-buttons";
      packageName = "angular-promise-buttons";
      version = "0.1.23";
      src = fetchurl {
        url = "https://registry.npmjs.org/angular-promise-buttons/-/angular-promise-buttons-0.1.23.tgz";
        sha512 = "LP57N1FgO9lybCDNJi6HrofSRpLnUtzsLgPg/k4LvFtSCiCZtFjf8uEsp274Q56w4lxXev4h5SGBhyuQ4uj7gw==";
      };
    };
    "angular-route-1.6.10" = {
      name = "angular-route";
      packageName = "angular-route";
      version = "1.6.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/angular-route/-/angular-route-1.6.10.tgz";
        sha512 = "BxjrjQNCbVqQKyB3nHjNI8zSUwhnQWFZnSBv5BZ336VbMKhWu74ad5xpFx5VMk6WyHlmMGDoRagzB6AKkRcvKA==";
      };
    };
    "angular-sanitize-1.6.10" = {
      name = "angular-sanitize";
      packageName = "angular-sanitize";
      version = "1.6.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/angular-sanitize/-/angular-sanitize-1.6.10.tgz";
        sha512 = "01i1Xoq9ykUrsoYQMSB6dWZmPp9Df5hfCqMAGGzJBWZ7L2WY0OtUphdI0YvR8ZF9lAsWtGNtsEFilObjq5nTgQ==";
      };
    };
    "angular-sweetalert-1.1.2" = {
      name = "angular-sweetalert";
      packageName = "angular-sweetalert";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/angular-sweetalert/-/angular-sweetalert-1.1.2.tgz";
        sha1 = "b5090c4e1fa486d9b61b9ea799d5b707bb04422f";
      };
    };
    "angular-touch-1.6.10" = {
      name = "angular-touch";
      packageName = "angular-touch";
      version = "1.6.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/angular-touch/-/angular-touch-1.6.10.tgz";
        sha512 = "ZblW46aN5s7OOihpXDa0qzrJXdaVGE44jc+a8e1NpOjhCKZDQze+nBHh3xw3toAF1BIfDJIkRstadk4h2R/uLg==";
      };
    };
    "angular-translate-2.18.4" = {
      name = "angular-translate";
      packageName = "angular-translate";
      version = "2.18.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/angular-translate/-/angular-translate-2.18.4.tgz";
        sha512 = "KohNrkH6J9PK+VW0L/nsRTcg5Fw70Ajwwe3Jbfm54Pf9u9Fd+wuingoKv+h45mKf38eT+Ouu51FPua8VmZNoCw==";
      };
    };
    "angular-ui-notification-0.3.6" = {
      name = "angular-ui-notification";
      packageName = "angular-ui-notification";
      version = "0.3.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/angular-ui-notification/-/angular-ui-notification-0.3.6.tgz";
        sha1 = "333bcbe82a2651482b39c3595b3cbfa88e30bcf7";
      };
    };
    "angular-utf8-base64-0.0.5" = {
      name = "angular-utf8-base64";
      packageName = "angular-utf8-base64";
      version = "0.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/angular-utf8-base64/-/angular-utf8-base64-0.0.5.tgz";
        sha1 = "95158d6809dbae1eb9fa03af45d67187b0788cf6";
      };
    };
    "angular-websocket-2.0.1" = {
      name = "angular-websocket";
      packageName = "angular-websocket";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/angular-websocket/-/angular-websocket-2.0.1.tgz";
        sha1 = "0fb4d60ed9018be583d031eec4e56b457cb8dcee";
      };
    };
    "angularjs-dragula-2.0.0" = {
      name = "angularjs-dragula";
      packageName = "angularjs-dragula";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/angularjs-dragula/-/angularjs-dragula-2.0.0.tgz";
        sha512 = "TkBnvt130FTRj5+g8ly6H6BlvZoBS7lnVRD+92WL5uKqR7PmX+UYWaiMOtO5kEMcQfRCeDZ/62xOvbekvGetMA==";
      };
    };
    "asn1.js-4.10.1" = {
      name = "asn1.js";
      packageName = "asn1.js";
      version = "4.10.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/asn1.js/-/asn1.js-4.10.1.tgz";
        sha512 = "p32cOF5q0Zqs9uBiONKYLm6BClCoBCM5O9JfeUSlnQLBTxYdTK+pW+nXflm8UkKd2UYlEbYz5qEi0JuZR9ckSw==";
      };
    };
    "assert-1.5.0" = {
      name = "assert";
      packageName = "assert";
      version = "1.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/assert/-/assert-1.5.0.tgz";
        sha512 = "EDsgawzwoun2CZkCgtxJbv392v4nbk9XDD06zI+kQYoBM/3RBWLlEyJARDOmhAAosBjWACEkKL6S+lIZtcAubA==";
      };
    };
    "atoa-1.0.0" = {
      name = "atoa";
      packageName = "atoa";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/atoa/-/atoa-1.0.0.tgz";
        sha1 = "0cc0e91a480e738f923ebc103676471779b34a49";
      };
    };
    "awesome-bootstrap-checkbox-0.3.7" = {
      name = "awesome-bootstrap-checkbox";
      packageName = "awesome-bootstrap-checkbox";
      version = "0.3.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/awesome-bootstrap-checkbox/-/awesome-bootstrap-checkbox-0.3.7.tgz";
        sha1 = "b112973ee6d5bff40ab217c420185c470251d0e2";
      };
    };
    "balanced-match-1.0.0" = {
      name = "balanced-match";
      packageName = "balanced-match";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/balanced-match/-/balanced-match-1.0.0.tgz";
        sha1 = "89b4d199ab2bee49de164ea02b89ce462d71b767";
      };
    };
    "base64-js-1.3.1" = {
      name = "base64-js";
      packageName = "base64-js";
      version = "1.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/base64-js/-/base64-js-1.3.1.tgz";
        sha512 = "mLQ4i2QO1ytvGWFWmcngKO//JXAQueZvwEKtjgQFM4jIK0kU+ytMfplL8j+n5mspOfjHwoAg+9yhb7BwAHm36g==";
      };
    };
    "bn.js-4.11.8" = {
      name = "bn.js";
      packageName = "bn.js";
      version = "4.11.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/bn.js/-/bn.js-4.11.8.tgz";
        sha512 = "ItfYfPLkWHUjckQCk8xC+LwxgK8NYcXywGigJgSwOP8Y2iyWT4f2vsZnoOXTTbo+o5yXmIUJ4gn5538SO5S3gA==";
      };
    };
    "bootstrap-3.4.1" = {
      name = "bootstrap";
      packageName = "bootstrap";
      version = "3.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/bootstrap/-/bootstrap-3.4.1.tgz";
        sha512 = "yN5oZVmRCwe5aKwzRj6736nSmKDX7pLYwsXiCj/EYmo16hODaBiT4En5btW/jhBF/seV+XMx3aYwukYC3A49DA==";
      };
    };
    "bootstrap-colorpicker-2.5.3" = {
      name = "bootstrap-colorpicker";
      packageName = "bootstrap-colorpicker";
      version = "2.5.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/bootstrap-colorpicker/-/bootstrap-colorpicker-2.5.3.tgz";
        sha512 = "xdllX8LSMvKULs3b8JrgRXTvyvjkSMHHHVuHjjN5FNMqr6kRe5NPiMHFmeAFjlgDF73MspikudLuEwR28LbzLw==";
      };
    };
    "bootstrap-contextmenu-1.0.0" = {
      name = "bootstrap-contextmenu";
      packageName = "bootstrap-contextmenu";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/bootstrap-contextmenu/-/bootstrap-contextmenu-1.0.0.tgz";
        sha1 = "e46467bc79527f75fc532552aab92a9cf688ccfb";
      };
    };
    "bootstrap-datepicker-1.9.0" = {
      name = "bootstrap-datepicker";
      packageName = "bootstrap-datepicker";
      version = "1.9.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/bootstrap-datepicker/-/bootstrap-datepicker-1.9.0.tgz";
        sha512 = "9rYYbaVOheGYxjOr/+bJCmRPihfy+LkLSg4fIFMT9Od8WwWB/MB50w0JO1eBgKUMbb7PFHQD5uAfI3ArAxZRXA==";
      };
    };
    "bootstrap-daterangepicker-2.1.30" = {
      name = "bootstrap-daterangepicker";
      packageName = "bootstrap-daterangepicker";
      version = "2.1.30";
      src = fetchurl {
        url = "https://registry.npmjs.org/bootstrap-daterangepicker/-/bootstrap-daterangepicker-2.1.30.tgz";
        sha1 = "f893dbfff5a4d7dfaab75460e8ea6969bb89689a";
      };
    };
    "bootstrap-slider-9.10.0" = {
      name = "bootstrap-slider";
      packageName = "bootstrap-slider";
      version = "9.10.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/bootstrap-slider/-/bootstrap-slider-9.10.0.tgz";
        sha1 = "1103d6bc00cfbfa8cfc9a2599ab518c55643da3f";
      };
    };
    "brace-expansion-1.1.11" = {
      name = "brace-expansion";
      packageName = "brace-expansion";
      version = "1.1.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/brace-expansion/-/brace-expansion-1.1.11.tgz";
        sha512 = "iCuPHDFgrHX7H2vEI/5xpz07zSHB00TpugqhmYtVmMO6518mCuRMoOYFldEBl0g187ufozdaHgWKcYFb61qGiA==";
      };
    };
    "brorand-1.1.0" = {
      name = "brorand";
      packageName = "brorand";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/brorand/-/brorand-1.1.0.tgz";
        sha1 = "12c25efe40a45e3c323eb8675a0a0ce57b22371f";
      };
    };
    "browser-pack-6.1.0" = {
      name = "browser-pack";
      packageName = "browser-pack";
      version = "6.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/browser-pack/-/browser-pack-6.1.0.tgz";
        sha512 = "erYug8XoqzU3IfcU8fUgyHqyOXqIE4tUTTQ+7mqUjQlvnXkOO6OlT9c/ZoJVHYoAaqGxr09CN53G7XIsO4KtWA==";
      };
    };
    "browser-resolve-1.11.3" = {
      name = "browser-resolve";
      packageName = "browser-resolve";
      version = "1.11.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/browser-resolve/-/browser-resolve-1.11.3.tgz";
        sha512 = "exDi1BYWB/6raKHmDTCicQfTkqwN5fioMFV4j8BsfMU4R2DK/QfZfK7kOVkmWCNANf0snkBzqGqAJBao9gZMdQ==";
      };
    };
    "browserify-16.5.1" = {
      name = "browserify";
      packageName = "browserify";
      version = "16.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/browserify/-/browserify-16.5.1.tgz";
        sha512 = "EQX0h59Pp+0GtSRb5rL6OTfrttlzv+uyaUVlK6GX3w11SQ0jKPKyjC/54RhPR2ib2KmfcELM06e8FxcI5XNU2A==";
      };
    };
    "browserify-aes-1.2.0" = {
      name = "browserify-aes";
      packageName = "browserify-aes";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/browserify-aes/-/browserify-aes-1.2.0.tgz";
        sha512 = "+7CHXqGuspUn/Sl5aO7Ea0xWGAtETPXNSAjHo48JfLdPWcMng33Xe4znFvQweqc/uzk5zSOI3H52CYnjCfb5hA==";
      };
    };
    "browserify-cipher-1.0.1" = {
      name = "browserify-cipher";
      packageName = "browserify-cipher";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/browserify-cipher/-/browserify-cipher-1.0.1.tgz";
        sha512 = "sPhkz0ARKbf4rRQt2hTpAHqn47X3llLkUGn+xEJzLjwY8LRs2p0v7ljvI5EyoRO/mexrNunNECisZs+gw2zz1w==";
      };
    };
    "browserify-des-1.0.2" = {
      name = "browserify-des";
      packageName = "browserify-des";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/browserify-des/-/browserify-des-1.0.2.tgz";
        sha512 = "BioO1xf3hFwz4kc6iBhI3ieDFompMhrMlnDFC4/0/vd5MokpuAc3R+LYbwTA9A5Yc9pq9UYPqffKpW2ObuwX5A==";
      };
    };
    "browserify-rsa-4.0.1" = {
      name = "browserify-rsa";
      packageName = "browserify-rsa";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/browserify-rsa/-/browserify-rsa-4.0.1.tgz";
        sha1 = "21e0abfaf6f2029cf2fafb133567a701d4135524";
      };
    };
    "browserify-sign-4.0.4" = {
      name = "browserify-sign";
      packageName = "browserify-sign";
      version = "4.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/browserify-sign/-/browserify-sign-4.0.4.tgz";
        sha1 = "aa4eb68e5d7b658baa6bf6a57e630cbd7a93d298";
      };
    };
    "browserify-zlib-0.2.0" = {
      name = "browserify-zlib";
      packageName = "browserify-zlib";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/browserify-zlib/-/browserify-zlib-0.2.0.tgz";
        sha512 = "Z942RysHXmJrhqk88FmKBVq/v5tqmSkDz7p54G/MGyjMnCFFnC79XWNbg+Vta8W6Wb2qtSZTSxIGkJrRpCFEiA==";
      };
    };
    "buffer-5.2.1" = {
      name = "buffer";
      packageName = "buffer";
      version = "5.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer/-/buffer-5.2.1.tgz";
        sha512 = "c+Ko0loDaFfuPWiL02ls9Xd3GO3cPVmUobQ6t3rXNUk304u6hGq+8N/kFi+QEIKhzK3uwolVhLzszmfLmMLnqg==";
      };
    };
    "buffer-from-1.1.1" = {
      name = "buffer-from";
      packageName = "buffer-from";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer-from/-/buffer-from-1.1.1.tgz";
        sha512 = "MQcXEUbCKtEo7bhqEs6560Hyd4XaovZlO/k9V3hjVUF/zwW7KBVdSK4gIt/bzwS9MbR5qob+F5jusZsb0YQK2A==";
      };
    };
    "buffer-xor-1.0.3" = {
      name = "buffer-xor";
      packageName = "buffer-xor";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer-xor/-/buffer-xor-1.0.3.tgz";
        sha1 = "26e61ed1422fb70dd42e6e36729ed51d855fe8d9";
      };
    };
    "builtin-status-codes-3.0.0" = {
      name = "builtin-status-codes";
      packageName = "builtin-status-codes";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/builtin-status-codes/-/builtin-status-codes-3.0.0.tgz";
        sha1 = "85982878e21b98e1c66425e03d0174788f569ee8";
      };
    };
    "cached-path-relative-1.0.2" = {
      name = "cached-path-relative";
      packageName = "cached-path-relative";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/cached-path-relative/-/cached-path-relative-1.0.2.tgz";
        sha512 = "5r2GqsoEb4qMTTN9J+WzXfjov+hjxT+j3u5K+kIVNIwAd99DLCJE9pBIMP1qVeybV6JiijL385Oz0DcYxfbOIg==";
      };
    };
    "charm-0.1.2" = {
      name = "charm";
      packageName = "charm";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/charm/-/charm-0.1.2.tgz";
        sha1 = "06c21eed1a1b06aeb67553cdc53e23274bac2296";
      };
    };
    "chart.js-1.1.1" = {
      name = "chart.js";
      packageName = "chart.js";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/chart.js/-/chart.js-1.1.1.tgz";
        sha1 = "a9b17054220bd45cbdb176fd6bcb8783ef871a7d";
      };
    };
    "cipher-base-1.0.4" = {
      name = "cipher-base";
      packageName = "cipher-base";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/cipher-base/-/cipher-base-1.0.4.tgz";
        sha512 = "Kkht5ye6ZGmwv40uUDZztayT2ThLQGfnj/T71N/XzeZeo3nf8foyW7zGTsPYkEya3m5f3cAypH+qe7YOrM1U2Q==";
      };
    };
    "ckeditor-4.12.1" = {
      name = "ckeditor";
      packageName = "ckeditor";
      version = "4.12.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ckeditor/-/ckeditor-4.12.1.tgz";
        sha512 = "pH2Su4oi0D4iN/3U8nUcwI7/lXHoOJi0aiN8e2zxnm4Ow5kq8eZP2ZGmpYyuqRyKZ2tHaU8+OyYi7laXcjiq9Q==";
      };
    };
    "classie-1.0.0" = {
      name = "classie";
      packageName = "classie";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/classie/-/classie-1.0.0.tgz";
        sha1 = "fc9b29b47e64e374a2062fb624d05a61cd703ab2";
      };
    };
    "combine-source-map-0.8.0" = {
      name = "combine-source-map";
      packageName = "combine-source-map";
      version = "0.8.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/combine-source-map/-/combine-source-map-0.8.0.tgz";
        sha1 = "a58d0df042c186fcf822a8e8015f5450d2d79a8b";
      };
    };
    "concat-map-0.0.1" = {
      name = "concat-map";
      packageName = "concat-map";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-map/-/concat-map-0.0.1.tgz";
        sha1 = "d8a96bd77fd68df7793a73036a3ba0d5405d477b";
      };
    };
    "concat-stream-1.6.2" = {
      name = "concat-stream";
      packageName = "concat-stream";
      version = "1.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-stream/-/concat-stream-1.6.2.tgz";
        sha512 = "27HBghJxjiZtIk3Ycvn/4kbJk/1uZuJFfuPEns6LaEvpvG1f0hTea8lilrouyo9mVc2GWdcEZ8OLoGmSADlrCw==";
      };
    };
    "console-browserify-1.2.0" = {
      name = "console-browserify";
      packageName = "console-browserify";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/console-browserify/-/console-browserify-1.2.0.tgz";
        sha512 = "ZMkYO/LkF17QvCPqM0gxw8yUzigAOZOSWSHg91FH6orS7vcEj5dVZTidN2fQ14yBSdg97RqhSNwLUXInd52OTA==";
      };
    };
    "constants-browserify-1.0.0" = {
      name = "constants-browserify";
      packageName = "constants-browserify";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/constants-browserify/-/constants-browserify-1.0.0.tgz";
        sha1 = "c20b96d8c617748aaf1c16021760cd27fcb8cb75";
      };
    };
    "contra-1.9.4" = {
      name = "contra";
      packageName = "contra";
      version = "1.9.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/contra/-/contra-1.9.4.tgz";
        sha1 = "f53bde42d7e5b5985cae4d99a8d610526de8f28d";
      };
    };
    "convert-source-map-1.1.3" = {
      name = "convert-source-map";
      packageName = "convert-source-map";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/convert-source-map/-/convert-source-map-1.1.3.tgz";
        sha1 = "4829c877e9fe49b3161f3bf3673888e204699860";
      };
    };
    "core-util-is-1.0.2" = {
      name = "core-util-is";
      packageName = "core-util-is";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/core-util-is/-/core-util-is-1.0.2.tgz";
        sha1 = "b5fd54220aa2bc5ab57aab7140c940754503c1a7";
      };
    };
    "create-ecdh-4.0.3" = {
      name = "create-ecdh";
      packageName = "create-ecdh";
      version = "4.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/create-ecdh/-/create-ecdh-4.0.3.tgz";
        sha512 = "GbEHQPMOswGpKXM9kCWVrremUcBmjteUaQ01T9rkKCPDXfUHX0IoP9LpHYo2NPFampa4e+/pFDc3jQdxrxQLaw==";
      };
    };
    "create-hash-1.2.0" = {
      name = "create-hash";
      packageName = "create-hash";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/create-hash/-/create-hash-1.2.0.tgz";
        sha512 = "z00bCGNHDG8mHAkP7CtT1qVu+bFQUPjYq/4Iv3C3kWjTFV10zIjfSoeqXo9Asws8gwSHDGj/hl2u4OGIjapeCg==";
      };
    };
    "create-hmac-1.1.7" = {
      name = "create-hmac";
      packageName = "create-hmac";
      version = "1.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/create-hmac/-/create-hmac-1.1.7.tgz";
        sha512 = "MJG9liiZ+ogc4TzUwuvbER1JRdgvUFSB5+VR/g5h82fGaIRWMWddtKBHi7/sVhfjQZ6SehlyhvQYrcYkaUIpLg==";
      };
    };
    "crossvent-1.5.4" = {
      name = "crossvent";
      packageName = "crossvent";
      version = "1.5.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/crossvent/-/crossvent-1.5.4.tgz";
        sha1 = "da2c4f8f40c94782517bf2beec1044148194ab92";
      };
    };
    "crypto-browserify-3.12.0" = {
      name = "crypto-browserify";
      packageName = "crypto-browserify";
      version = "3.12.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/crypto-browserify/-/crypto-browserify-3.12.0.tgz";
        sha512 = "fz4spIh+znjO2VjL+IdhEpRJ3YN6sMzITSBijk6FK2UvTqruSQW+/cCZTSNsMiZNvUeq0CqurF+dAbyiGOY6Wg==";
      };
    };
    "custom-event-1.0.0" = {
      name = "custom-event";
      packageName = "custom-event";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/custom-event/-/custom-event-1.0.0.tgz";
        sha1 = "2e4628be19dc4b214b5c02630c5971e811618062";
      };
    };
    "dash-ast-1.0.0" = {
      name = "dash-ast";
      packageName = "dash-ast";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/dash-ast/-/dash-ast-1.0.0.tgz";
        sha512 = "Vy4dx7gquTeMcQR/hDkYLGUnwVil6vk4FOOct+djUnHOUWt+zJPJAaRIXaAFkPXtJjvlY7o3rfRu0/3hpnwoUA==";
      };
    };
    "datatables.net-1.10.20" = {
      name = "datatables.net";
      packageName = "datatables.net";
      version = "1.10.20";
      src = fetchurl {
        url = "https://registry.npmjs.org/datatables.net/-/datatables.net-1.10.20.tgz";
        sha512 = "4E4S7tTU607N3h0fZPkGmAtr9mwy462u+VJ6gxYZ8MxcRIjZqHy3Dv1GNry7i3zQCktTdWbULVKBbkAJkuHEnQ==";
      };
    };
    "datatables.net-bs-1.10.20" = {
      name = "datatables.net-bs";
      packageName = "datatables.net-bs";
      version = "1.10.20";
      src = fetchurl {
        url = "https://registry.npmjs.org/datatables.net-bs/-/datatables.net-bs-1.10.20.tgz";
        sha512 = "NsMoOOYZ6NlteOpzhltw21lXsNdhjIMbIOxnqmcrb62ntl8eL9pYzk2AeiDXBlIKY4e550ZrExCq3CYKQ9myEg==";
      };
    };
    "defined-1.0.0" = {
      name = "defined";
      packageName = "defined";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/defined/-/defined-1.0.0.tgz";
        sha1 = "c98d9bcef75674188e110969151199e39b1fa693";
      };
    };
    "deps-sort-2.0.1" = {
      name = "deps-sort";
      packageName = "deps-sort";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/deps-sort/-/deps-sort-2.0.1.tgz";
        sha512 = "1orqXQr5po+3KI6kQb9A4jnXT1PBwggGl2d7Sq2xsnOeI9GPcE/tGcF9UiSZtZBM7MukY4cAh7MemS6tZYipfw==";
      };
    };
    "des.js-1.0.1" = {
      name = "des.js";
      packageName = "des.js";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/des.js/-/des.js-1.0.1.tgz";
        sha512 = "Q0I4pfFrv2VPd34/vfLrFOoRmlYj3OV50i7fskps1jZWK1kApMWWT9G6RRUeYedLcBDIhnSDaUvJMb3AhUlaEA==";
      };
    };
    "detective-5.2.0" = {
      name = "detective";
      packageName = "detective";
      version = "5.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/detective/-/detective-5.2.0.tgz";
        sha512 = "6SsIx+nUUbuK0EthKjv0zrdnajCCXVYGmbYYiYjFVpzcjwEs/JMDZ8tPRG29J/HhN56t3GJp2cGSWDRjjot8Pg==";
      };
    };
    "diffie-hellman-5.0.3" = {
      name = "diffie-hellman";
      packageName = "diffie-hellman";
      version = "5.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/diffie-hellman/-/diffie-hellman-5.0.3.tgz";
        sha512 = "kqag/Nl+f3GwyK25fhUMYj81BUOrZ9IuJsjIcDE5icNM9FJHAVm3VcUDxdLPoQtTuUylWm6ZIknYJwwaPxsUzg==";
      };
    };
    "domain-browser-1.2.0" = {
      name = "domain-browser";
      packageName = "domain-browser";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/domain-browser/-/domain-browser-1.2.0.tgz";
        sha512 = "jnjyiM6eRyZl2H+W8Q/zLMA481hzi0eszAaBUzIVnmYVDBbnLxVNnfu1HgEBvCbL+71FrxMl3E6lpKH7Ge3OXA==";
      };
    };
    "domhelper-0.9.1" = {
      name = "domhelper";
      packageName = "domhelper";
      version = "0.9.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/domhelper/-/domhelper-0.9.1.tgz";
        sha1 = "26554e5bac2c9e9585dca500978df5067d64bd00";
      };
    };
    "dragula-3.7.2" = {
      name = "dragula";
      packageName = "dragula";
      version = "3.7.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/dragula/-/dragula-3.7.2.tgz";
        sha1 = "4a35c9d3981ffac1a949c29ca7285058e87393ce";
      };
    };
    "duplexer2-0.1.4" = {
      name = "duplexer2";
      packageName = "duplexer2";
      version = "0.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/duplexer2/-/duplexer2-0.1.4.tgz";
        sha1 = "8b12dab878c0d69e3e7891051662a32fc6bddcc1";
      };
    };
    "echarts-3.8.5" = {
      name = "echarts";
      packageName = "echarts";
      version = "3.8.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/echarts/-/echarts-3.8.5.tgz";
        sha512 = "E+nnROMfCeiLeoT/fZyX8SE8mKzwkTjyemyoBF543oqjRtjTSKQAVDEihMXy4oC6pJS0tYGdMqCA2ATk8onyRg==";
      };
    };
    "elliptic-6.5.2" = {
      name = "elliptic";
      packageName = "elliptic";
      version = "6.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/elliptic/-/elliptic-6.5.2.tgz";
        sha512 = "f4x70okzZbIQl/NSRLkI/+tteV/9WqL98zx+SQ69KbXxmVrmjwsNUPn/gYJJ0sHvEak24cZgHIPegRePAtA/xw==";
      };
    };
    "eve-raphael-0.5.0" = {
      name = "eve-raphael";
      packageName = "eve-raphael";
      version = "0.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/eve-raphael/-/eve-raphael-0.5.0.tgz";
        sha1 = "17c754b792beef3fa6684d79cf5a47c63c4cda30";
      };
    };
    "events-2.1.0" = {
      name = "events";
      packageName = "events";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/events/-/events-2.1.0.tgz";
        sha512 = "3Zmiobend8P9DjmKAty0Era4jV8oJ0yGYe2nJJAxgymF9+N8F2m0hhZiMoWtcfepExzNKZumFU3ksdQbInGWCg==";
      };
    };
    "evp_bytestokey-1.0.3" = {
      name = "evp_bytestokey";
      packageName = "evp_bytestokey";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/evp_bytestokey/-/evp_bytestokey-1.0.3.tgz";
        sha512 = "/f2Go4TognH/KvCISP7OUsHn85hT9nUkxxA9BEWxFn+Oj9o8ZNLm/40hdlgSLyuOimsrTKLUMEorQexp/aPQeA==";
      };
    };
    "fast-safe-stringify-2.0.7" = {
      name = "fast-safe-stringify";
      packageName = "fast-safe-stringify";
      version = "2.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-safe-stringify/-/fast-safe-stringify-2.0.7.tgz";
        sha512 = "Utm6CdzT+6xsDk2m8S6uL8VHxNwI6Jub+e9NYTcAms28T84pTa25GJQV9j0CY0N1rM8hK4x6grpF2BQf+2qwVA==";
      };
    };
    "fastclick-1.0.6" = {
      name = "fastclick";
      packageName = "fastclick";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/fastclick/-/fastclick-1.0.6.tgz";
        sha1 = "161625b27b1a5806405936bda9a2c1926d06be6a";
      };
    };
    "flot-0.8.3" = {
      name = "flot";
      packageName = "flot";
      version = "0.8.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/flot/-/flot-0.8.3.tgz";
        sha512 = "xg2otcTJDvS+ERK+my4wxG/ASq90QURXtoM4LhacCq0jQW2jbyjdttbRNqU2cPykrpMvJ6b2uSp6SAgYAzj9tQ==";
      };
    };
    "font-awesome-4.7.0" = {
      name = "font-awesome";
      packageName = "font-awesome";
      version = "4.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/font-awesome/-/font-awesome-4.7.0.tgz";
        sha1 = "8fa8cf0411a1a31afd07b06d2902bb9fc815a133";
      };
    };
    "fs.realpath-1.0.0" = {
      name = "fs.realpath";
      packageName = "fs.realpath";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs.realpath/-/fs.realpath-1.0.0.tgz";
        sha1 = "1504ad2523158caa40db4a2787cb01411994ea4f";
      };
    };
    "fullcalendar-3.10.1" = {
      name = "fullcalendar";
      packageName = "fullcalendar";
      version = "3.10.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/fullcalendar/-/fullcalendar-3.10.1.tgz";
        sha512 = "E0ioaHVmwdS4es8pNTUNva7505wPkUMFdn9JGFLYo+J12ARhN3zDBwoPj2DfB8rL7Yc1sSve+FqDHC3s2SZ7Fw==";
      };
    };
    "function-bind-1.1.1" = {
      name = "function-bind";
      packageName = "function-bind";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/function-bind/-/function-bind-1.1.1.tgz";
        sha512 = "yIovAzMX49sF8Yl58fSCWJ5svSLuaibPxXQJFLmBObTuCr0Mf1KiPopGM9NiFjiYBCbfaa2Fh6breQ6ANVTI0A==";
      };
    };
    "get-assigned-identifiers-1.2.0" = {
      name = "get-assigned-identifiers";
      packageName = "get-assigned-identifiers";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-assigned-identifiers/-/get-assigned-identifiers-1.2.0.tgz";
        sha512 = "mBBwmeGTrxEMO4pMaaf/uUEFHnYtwr8FTe8Y/mer4rcV/bye0qGm6pw1bGZFGStxC5O76c5ZAVBGnqHmOaJpdQ==";
      };
    };
    "glob-7.1.2" = {
      name = "glob";
      packageName = "glob";
      version = "7.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-7.1.2.tgz";
        sha512 = "MJTUg1kjuLeQCJ+ccE4Vpa6kKVXkPYJ2mOCQyUuKLcLQsdrMCpBPUi8qVE6+YuaJkozeA9NusTAw3hLr8Xe5EQ==";
      };
    };
    "has-1.0.3" = {
      name = "has";
      packageName = "has";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/has/-/has-1.0.3.tgz";
        sha512 = "f2dvO0VU6Oej7RkWJGrehjbzMAjFp5/VKPp5tTpWIV4JHHZK1/BxbFRtf/siA2SWTe09caDmVtYYzWEIbBS4zw==";
      };
    };
    "hash-base-3.0.4" = {
      name = "hash-base";
      packageName = "hash-base";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/hash-base/-/hash-base-3.0.4.tgz";
        sha1 = "5fc8686847ecd73499403319a6b0a3f3f6ae4918";
      };
    };
    "hash.js-1.1.7" = {
      name = "hash.js";
      packageName = "hash.js";
      version = "1.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/hash.js/-/hash.js-1.1.7.tgz";
        sha512 = "taOaskGt4z4SOANNseOviYDvjEJinIkRgmp7LbKP2YTTmVxWBl87s/uzK9r+44BclBSp2X7K1hqeNfz9JbBeXA==";
      };
    };
    "hmac-drbg-1.0.1" = {
      name = "hmac-drbg";
      packageName = "hmac-drbg";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/hmac-drbg/-/hmac-drbg-1.0.1.tgz";
        sha1 = "d2745701025a6c775a6c545793ed502fc0c649a1";
      };
    };
    "htmlescape-1.1.1" = {
      name = "htmlescape";
      packageName = "htmlescape";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/htmlescape/-/htmlescape-1.1.1.tgz";
        sha1 = "3a03edc2214bca3b66424a3e7959349509cb0351";
      };
    };
    "https-browserify-1.0.0" = {
      name = "https-browserify";
      packageName = "https-browserify";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/https-browserify/-/https-browserify-1.0.0.tgz";
        sha1 = "ec06c10e0a34c0f2faf199f7fd7fc78fffd03c73";
      };
    };
    "ieee754-1.1.13" = {
      name = "ieee754";
      packageName = "ieee754";
      version = "1.1.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/ieee754/-/ieee754-1.1.13.tgz";
        sha512 = "4vf7I2LYV/HaWerSo3XmlMkp5eZ83i+/CDluXi/IGTs/O1sejBNhTtnxzmRZfvOUqj7lZjqHkeTvpgSFDlWZTg==";
      };
    };
    "inflight-1.0.6" = {
      name = "inflight";
      packageName = "inflight";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/inflight/-/inflight-1.0.6.tgz";
        sha1 = "49bd6331d7d02d0c09bc910a1075ba8165b56df9";
      };
    };
    "inherits-2.0.1" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.1.tgz";
        sha1 = "b17d08d326b4423e568eff719f91b0b1cbdf69f1";
      };
    };
    "inherits-2.0.3" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.3.tgz";
        sha1 = "633c2c83e3da42a502f52466022480f4208261de";
      };
    };
    "inline-source-map-0.6.2" = {
      name = "inline-source-map";
      packageName = "inline-source-map";
      version = "0.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/inline-source-map/-/inline-source-map-0.6.2.tgz";
        sha1 = "f9393471c18a79d1724f863fa38b586370ade2a5";
      };
    };
    "inputmask-3.3.11" = {
      name = "inputmask";
      packageName = "inputmask";
      version = "3.3.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/inputmask/-/inputmask-3.3.11.tgz";
        sha1 = "1421c94ae28c3dcd1b4d26337b508bb34998e2d8";
      };
    };
    "insert-module-globals-7.2.0" = {
      name = "insert-module-globals";
      packageName = "insert-module-globals";
      version = "7.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/insert-module-globals/-/insert-module-globals-7.2.0.tgz";
        sha512 = "VE6NlW+WGn2/AeOMd496AHFYmE7eLKkUY6Ty31k4og5vmA3Fjuwe9v6ifH6Xx/Hz27QvdoMoviw1/pqWRB09Sw==";
      };
    };
    "ion-rangeslider-2.3.1" = {
      name = "ion-rangeslider";
      packageName = "ion-rangeslider";
      version = "2.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ion-rangeslider/-/ion-rangeslider-2.3.1.tgz";
        sha512 = "6V+24FD13/feliI485gnRHZYD9Ev64M5NAFTxnVib516ATHa9PlXQrC+nOiPngouRYTCLPJyokAJEi3e1Umi5g==";
      };
    };
    "ionicons-3.0.0" = {
      name = "ionicons";
      packageName = "ionicons";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ionicons/-/ionicons-3.0.0.tgz";
        sha1 = "40b8daf4fd7a31150bd002160f66496e22a98c3c";
      };
    };
    "is-buffer-1.1.6" = {
      name = "is-buffer";
      packageName = "is-buffer";
      version = "1.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-buffer/-/is-buffer-1.1.6.tgz";
        sha512 = "NcdALwpXkTm5Zvvbk7owOUSvVvBKDgKP5/ewfXEznmQFfs4ZRmanOeKBTjRVjka3QFoN6XJ+9F3USqfHqTaU5w==";
      };
    };
    "isarray-1.0.0" = {
      name = "isarray";
      packageName = "isarray";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isarray/-/isarray-1.0.0.tgz";
        sha1 = "bb935d48582cba168c06834957a54a3e07124f11";
      };
    };
    "jquery-3.4.1" = {
      name = "jquery";
      packageName = "jquery";
      version = "3.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jquery/-/jquery-3.4.1.tgz";
        sha512 = "36+AdBzCL+y6qjw5Tx7HgzeGCzC81MDDgaUP8ld2zhx58HdqXGoBd+tHdrBMiyjGQs0Hxs/MLZTu/eHNJJuWPw==";
      };
    };
    "jquery-knob-1.2.11" = {
      name = "jquery-knob";
      packageName = "jquery-knob";
      version = "1.2.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/jquery-knob/-/jquery-knob-1.2.11.tgz";
        sha1 = "f37c39dbc1c7a6a6c12cdb2ed4f6bffb683f10d6";
      };
    };
    "jquery-slimscroll-1.3.8" = {
      name = "jquery-slimscroll";
      packageName = "jquery-slimscroll";
      version = "1.3.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/jquery-slimscroll/-/jquery-slimscroll-1.3.8.tgz";
        sha1 = "8481c44e7a47687653908a28f7f70aed64c84e36";
      };
    };
    "jquery-sparkline-2.4.0" = {
      name = "jquery-sparkline";
      packageName = "jquery-sparkline";
      version = "2.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jquery-sparkline/-/jquery-sparkline-2.4.0.tgz";
        sha1 = "1be8b7b704dd3857152708aefb1d4a4b3a69fb33";
      };
    };
    "jquery-ui-1.12.1" = {
      name = "jquery-ui";
      packageName = "jquery-ui";
      version = "1.12.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jquery-ui/-/jquery-ui-1.12.1.tgz";
        sha1 = "bcb4045c8dd0539c134bc1488cdd3e768a7a9e51";
      };
    };
    "json-stable-stringify-0.0.1" = {
      name = "json-stable-stringify";
      packageName = "json-stable-stringify";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-stable-stringify/-/json-stable-stringify-0.0.1.tgz";
        sha1 = "611c23e814db375527df851193db59dd2af27f45";
      };
    };
    "jsonify-0.0.0" = {
      name = "jsonify";
      packageName = "jsonify";
      version = "0.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonify/-/jsonify-0.0.0.tgz";
        sha1 = "2c74b6ee41d93ca51b7b5aaee8f503631d252a73";
      };
    };
    "jsonparse-1.3.1" = {
      name = "jsonparse";
      packageName = "jsonparse";
      version = "1.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonparse/-/jsonparse-1.3.1.tgz";
        sha1 = "3f4dae4a91fac315f71062f8521cc239f1366280";
      };
    };
    "jvectormap-1.2.2" = {
      name = "jvectormap";
      packageName = "jvectormap";
      version = "1.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/jvectormap/-/jvectormap-1.2.2.tgz";
        sha1 = "2e4408b24a60473ff106c1e7243e375ae5ca85da";
      };
    };
    "labeled-stream-splicer-2.0.2" = {
      name = "labeled-stream-splicer";
      packageName = "labeled-stream-splicer";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/labeled-stream-splicer/-/labeled-stream-splicer-2.0.2.tgz";
        sha512 = "Ca4LSXFFZUjPScRaqOcFxneA0VpKZr4MMYCljyQr4LIewTLb3Y0IUTIsnBBsVubIeEfxeSZpSjSsRM8APEQaAw==";
      };
    };
    "lodash.memoize-3.0.4" = {
      name = "lodash.memoize";
      packageName = "lodash.memoize";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.memoize/-/lodash.memoize-3.0.4.tgz";
        sha1 = "2dcbd2c287cbc0a55cc42328bd0c736150d53e3f";
      };
    };
    "md5.js-1.3.5" = {
      name = "md5.js";
      packageName = "md5.js";
      version = "1.3.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/md5.js/-/md5.js-1.3.5.tgz";
        sha512 = "xitP+WxNPcTTOgnTJcrhM0xvdPepipPSf3I8EIpGKeFLjt3PlJLIDG3u8EX53ZIubkb+5U2+3rELYpEhHhzdkg==";
      };
    };
    "miller-rabin-4.0.1" = {
      name = "miller-rabin";
      packageName = "miller-rabin";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/miller-rabin/-/miller-rabin-4.0.1.tgz";
        sha512 = "115fLhvZVqWwHPbClyntxEVfVDfl9DLLTuJvq3g2O/Oxi8AiNouAHvDSzHS0viUJc+V5vm3eq91Xwqn9dp4jRA==";
      };
    };
    "minimalistic-assert-1.0.1" = {
      name = "minimalistic-assert";
      packageName = "minimalistic-assert";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimalistic-assert/-/minimalistic-assert-1.0.1.tgz";
        sha512 = "UtJcAD4yEaGtjPezWuO9wC4nwUnVH/8/Im3yEHQP4b67cXlD/Qr9hdITCU1xDbSEXg2XKNaP8jsReV7vQd00/A==";
      };
    };
    "minimalistic-crypto-utils-1.0.1" = {
      name = "minimalistic-crypto-utils";
      packageName = "minimalistic-crypto-utils";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimalistic-crypto-utils/-/minimalistic-crypto-utils-1.0.1.tgz";
        sha1 = "f6c00c1c0b082246e5c4d99dfb8c7c083b2b582a";
      };
    };
    "minimatch-3.0.4" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-3.0.4.tgz";
        sha512 = "yJHVQEhyqPLUTgt9B83PXu6W3rx4MvvHvSUvToogpwoGDOUQ+yDrR0HRot+yOCdCO7u4hX3pWft6kWBBcqh0UA==";
      };
    };
    "minimist-1.2.0" = {
      name = "minimist";
      packageName = "minimist";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-1.2.0.tgz";
        sha1 = "a35008b20f41383eec1fb914f4cd5df79a264284";
      };
    };
    "mkdirp-classic-0.5.2" = {
      name = "mkdirp-classic";
      packageName = "mkdirp-classic";
      version = "0.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/mkdirp-classic/-/mkdirp-classic-0.5.2.tgz";
        sha512 = "ejdnDQcR75gwknmMw/tx02AuRs8jCtqFoFqDZMjiNxsu85sRIJVXDKHuLYvUUPRBUtV2FpSZa9bL1BUa3BdR2g==";
      };
    };
    "module-deps-6.2.2" = {
      name = "module-deps";
      packageName = "module-deps";
      version = "6.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/module-deps/-/module-deps-6.2.2.tgz";
        sha512 = "a9y6yDv5u5I4A+IPHTnqFxcaKr4p50/zxTjcQJaX2ws9tN/W6J6YXnEKhqRyPhl494dkcxx951onSKVezmI+3w==";
      };
    };
    "moment-2.24.0" = {
      name = "moment";
      packageName = "moment";
      version = "2.24.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/moment/-/moment-2.24.0.tgz";
        sha512 = "bV7f+6l2QigeBBZSM/6yTNq4P2fNpSWj/0e7jQcy87A8e7o2nAfP/34/2ky5Vw4B9S446EtIhodAzkFCcR4dQg==";
      };
    };
    "moment-timezone-0.5.28" = {
      name = "moment-timezone";
      packageName = "moment-timezone";
      version = "0.5.28";
      src = fetchurl {
        url = "https://registry.npmjs.org/moment-timezone/-/moment-timezone-0.5.28.tgz";
        sha512 = "TDJkZvAyKIVWg5EtVqRzU97w0Rb0YVbfpqyjgu6GwXCAohVRqwZjf4fOzDE6p1Ch98Sro/8hQQi65WDXW5STPw==";
      };
    };
    "morris.js-0.5.0" = {
      name = "morris.js";
      packageName = "morris.js";
      version = "0.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/morris.js/-/morris.js-0.5.0.tgz";
        sha1 = "725767135cfae059aae75999bb2ce6a1c5d1b44b";
      };
    };
    "natural-compare-1.4.0" = {
      name = "natural-compare";
      packageName = "natural-compare";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/natural-compare/-/natural-compare-1.4.0.tgz";
        sha1 = "4abebfeed7541f2c27acfb29bdbbd15c8d5ba4f7";
      };
    };
    "object-assign-4.1.1" = {
      name = "object-assign";
      packageName = "object-assign";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-assign/-/object-assign-4.1.1.tgz";
        sha1 = "2109adc7965887cfc05cbbd442cac8bfbb360863";
      };
    };
    "once-1.4.0" = {
      name = "once";
      packageName = "once";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/once/-/once-1.4.0.tgz";
        sha1 = "583b1aa775961d4b113ac17d9c50baef9dd76bd1";
      };
    };
    "options-0.0.6" = {
      name = "options";
      packageName = "options";
      version = "0.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/options/-/options-0.0.6.tgz";
        sha1 = "ec22d312806bb53e731773e7cdaefcf1c643128f";
      };
    };
    "os-browserify-0.3.0" = {
      name = "os-browserify";
      packageName = "os-browserify";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/os-browserify/-/os-browserify-0.3.0.tgz";
        sha1 = "854373c7f5c2315914fc9bfc6bd8238fdda1ec27";
      };
    };
    "pace-0.0.4" = {
      name = "pace";
      packageName = "pace";
      version = "0.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/pace/-/pace-0.0.4.tgz";
        sha1 = "d66405d5f5bc12d25441a6e26c878dbc69e77a77";
      };
    };
    "pako-1.0.11" = {
      name = "pako";
      packageName = "pako";
      version = "1.0.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/pako/-/pako-1.0.11.tgz";
        sha512 = "4hLB8Py4zZce5s4yd9XzopqwVv/yGNhV1Bl8NTmCq1763HeK2+EwVTv+leGeL13Dnh2wfbqowVPXCIO0z4taYw==";
      };
    };
    "parents-1.0.1" = {
      name = "parents";
      packageName = "parents";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/parents/-/parents-1.0.1.tgz";
        sha1 = "fedd4d2bf193a77745fe71e371d73c3307d9c751";
      };
    };
    "parse-asn1-5.1.5" = {
      name = "parse-asn1";
      packageName = "parse-asn1";
      version = "5.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/parse-asn1/-/parse-asn1-5.1.5.tgz";
        sha512 = "jkMYn1dcJqF6d5CpU689bq7w/b5ALS9ROVSpQDPrZsqqesUJii9qutvoT5ltGedNXMO2e16YUWIghG9KxaViTQ==";
      };
    };
    "path-browserify-0.0.1" = {
      name = "path-browserify";
      packageName = "path-browserify";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-browserify/-/path-browserify-0.0.1.tgz";
        sha512 = "BapA40NHICOS+USX9SN4tyhq+A2RrN/Ws5F0Z5aMHDp98Fl86lX8Oti8B7uN93L4Ifv4fHOEA+pQw87gmMO/lQ==";
      };
    };
    "path-is-absolute-1.0.1" = {
      name = "path-is-absolute";
      packageName = "path-is-absolute";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-is-absolute/-/path-is-absolute-1.0.1.tgz";
        sha1 = "174b9268735534ffbc7ace6bf53a5a9e1b5c5f5f";
      };
    };
    "path-parse-1.0.6" = {
      name = "path-parse";
      packageName = "path-parse";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-parse/-/path-parse-1.0.6.tgz";
        sha512 = "GSmOT2EbHrINBf9SR7CDELwlJ8AENk3Qn7OikK4nFYAu3Ote2+JYNVvkpAEQm3/TLNEJFD/xZJjzyxg3KBWOzw==";
      };
    };
    "path-platform-0.11.15" = {
      name = "path-platform";
      packageName = "path-platform";
      version = "0.11.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-platform/-/path-platform-0.11.15.tgz";
        sha1 = "e864217f74c36850f0852b78dc7bf7d4a5721bf2";
      };
    };
    "pbkdf2-3.0.17" = {
      name = "pbkdf2";
      packageName = "pbkdf2";
      version = "3.0.17";
      src = fetchurl {
        url = "https://registry.npmjs.org/pbkdf2/-/pbkdf2-3.0.17.tgz";
        sha512 = "U/il5MsrZp7mGg3mSQfn742na2T+1/vHDCG5/iTI3X9MKUuYUZVLQhyRsg06mCgDBTd57TxzgZt7P+fYfjRLtA==";
      };
    };
    "process-0.11.10" = {
      name = "process";
      packageName = "process";
      version = "0.11.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/process/-/process-0.11.10.tgz";
        sha1 = "7332300e840161bda3e69a1d1d91a7d4bc16f182";
      };
    };
    "process-nextick-args-2.0.0" = {
      name = "process-nextick-args";
      packageName = "process-nextick-args";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/process-nextick-args/-/process-nextick-args-2.0.0.tgz";
        sha512 = "MtEC1TqN0EU5nephaJ4rAtThHtC86dNN9qCuEhtshvpVBkAW5ZO7BASN9REnF9eoXGcRub+pFuKEpOHE+HbEMw==";
      };
    };
    "public-encrypt-4.0.3" = {
      name = "public-encrypt";
      packageName = "public-encrypt";
      version = "4.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/public-encrypt/-/public-encrypt-4.0.3.tgz";
        sha512 = "zVpa8oKZSz5bTMTFClc1fQOnyyEzpl5ozpi1B5YcvBrdohMjH2rfsBtyXcuNuwjsDIXmBYlF2N5FlJYhR29t8Q==";
      };
    };
    "punycode-1.3.2" = {
      name = "punycode";
      packageName = "punycode";
      version = "1.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/punycode/-/punycode-1.3.2.tgz";
        sha1 = "9653a036fb7c1ee42342f2325cceefea3926c48d";
      };
    };
    "punycode-1.4.1" = {
      name = "punycode";
      packageName = "punycode";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/punycode/-/punycode-1.4.1.tgz";
        sha1 = "c0d5a63b2718800ad8e1eb0fa5269c84dd41845e";
      };
    };
    "querystring-0.2.0" = {
      name = "querystring";
      packageName = "querystring";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/querystring/-/querystring-0.2.0.tgz";
        sha1 = "b209849203bb25df820da756e747005878521620";
      };
    };
    "querystring-es3-0.2.1" = {
      name = "querystring-es3";
      packageName = "querystring-es3";
      version = "0.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/querystring-es3/-/querystring-es3-0.2.1.tgz";
        sha1 = "9ec61f79049875707d69414596fd907a4d711e73";
      };
    };
    "randombytes-2.1.0" = {
      name = "randombytes";
      packageName = "randombytes";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/randombytes/-/randombytes-2.1.0.tgz";
        sha512 = "vYl3iOX+4CKUWuxGi9Ukhie6fsqXqS9FE2Zaic4tNFD2N2QQaXOMFbuKK4QmDHC0JO6B1Zp41J0LpT0oR68amQ==";
      };
    };
    "randomfill-1.0.4" = {
      name = "randomfill";
      packageName = "randomfill";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/randomfill/-/randomfill-1.0.4.tgz";
        sha512 = "87lcbR8+MhcWcUiQ+9e+Rwx8MyR2P7qnt15ynUlbm3TU/fjbgz4GsvfSUDTemtCCtVCqb4ZcEFlyPNTh9bBTLw==";
      };
    };
    "raphael-2.3.0" = {
      name = "raphael";
      packageName = "raphael";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/raphael/-/raphael-2.3.0.tgz";
        sha512 = "w2yIenZAQnp257XUWGni4bLMVxpUpcIl7qgxEgDIXtmSypYtlNxfXWpOBxs7LBTps5sDwhRnrToJrMUrivqNTQ==";
      };
    };
    "read-only-stream-2.0.0" = {
      name = "read-only-stream";
      packageName = "read-only-stream";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/read-only-stream/-/read-only-stream-2.0.0.tgz";
        sha1 = "2724fd6a8113d73764ac288d4386270c1dbf17f0";
      };
    };
    "readable-stream-2.3.6" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "2.3.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-2.3.6.tgz";
        sha512 = "tQtKA9WIAhBF3+VLAseyMqZeBjW0AHJoxOtYqSUZNJxauErmLbVm2FW1y+J/YA9dUrAC39ITejlZWhVIwawkKw==";
      };
    };
    "readable-stream-3.6.0" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "3.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-3.6.0.tgz";
        sha512 = "BViHy7LKeTz4oNnkcLJ+lVSL6vpiFeX6/d3oSH8zCW7UxP2onchk+vTGB143xuFjHS3deTgkKoXXymXqymiIdA==";
      };
    };
    "resolve-1.1.7" = {
      name = "resolve";
      packageName = "resolve";
      version = "1.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve/-/resolve-1.1.7.tgz";
        sha1 = "203114d82ad2c5ed9e8e0411b3932875e889e97b";
      };
    };
    "resolve-1.8.1" = {
      name = "resolve";
      packageName = "resolve";
      version = "1.8.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve/-/resolve-1.8.1.tgz";
        sha512 = "AicPrAC7Qu1JxPCZ9ZgCZlY35QgFnNqc+0LtbRNxnVw4TXvjQ72wnuL9JQcEBgXkI9JM8MsT9kaQoHcpCRJOYA==";
      };
    };
    "ripemd160-2.0.2" = {
      name = "ripemd160";
      packageName = "ripemd160";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ripemd160/-/ripemd160-2.0.2.tgz";
        sha512 = "ii4iagi25WusVoiC4B4lq7pbXfAp3D9v5CwfkY33vffw2+pkDjY1D8GaN7spsxvCSx8dkPqOZCEZyfxcmJG2IA==";
      };
    };
    "safe-buffer-5.1.2" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.1.2.tgz";
        sha512 = "Gd2UZBJDkXlY7GbJxfsE8/nvKkUEU1G38c1siN6QP6a9PT9MmHB8GnpscSmMJSoF8LOIrt8ud/wPtojys4G6+g==";
      };
    };
    "select2-4.0.13" = {
      name = "select2";
      packageName = "select2";
      version = "4.0.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/select2/-/select2-4.0.13.tgz";
        sha512 = "1JeB87s6oN/TDxQQYCvS5EFoQyvV6eYMZZ0AeA4tdFDYWN3BAGZ8npr17UBFddU0lgAt3H0yjX3X6/ekOj1yjw==";
      };
    };
    "sha.js-2.4.11" = {
      name = "sha.js";
      packageName = "sha.js";
      version = "2.4.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/sha.js/-/sha.js-2.4.11.tgz";
        sha512 = "QMEp5B7cftE7APOjk5Y6xgrbWu+WkLVQwk8JNjZ8nKRciZaByEW6MubieAiToS7+dwvrjGhH8jRXz3MVd0AYqQ==";
      };
    };
    "shasum-1.0.2" = {
      name = "shasum";
      packageName = "shasum";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/shasum/-/shasum-1.0.2.tgz";
        sha1 = "e7012310d8f417f4deb5712150e5678b87ae565f";
      };
    };
    "shasum-object-1.0.0" = {
      name = "shasum-object";
      packageName = "shasum-object";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/shasum-object/-/shasum-object-1.0.0.tgz";
        sha512 = "Iqo5rp/3xVi6M4YheapzZhhGPVs0yZwHj7wvwQ1B9z8H6zk+FEnI7y3Teq7qwnekfEhu8WmG2z0z4iWZaxLWVg==";
      };
    };
    "shell-quote-1.7.2" = {
      name = "shell-quote";
      packageName = "shell-quote";
      version = "1.7.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/shell-quote/-/shell-quote-1.7.2.tgz";
        sha512 = "mRz/m/JVscCrkMyPqHc/bczi3OQHkLTqXHEFu0zDhK/qfv3UcOA4SVmRCLmos4bhjr9ekVQubj/R7waKapmiQg==";
      };
    };
    "simple-concat-1.0.0" = {
      name = "simple-concat";
      packageName = "simple-concat";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/simple-concat/-/simple-concat-1.0.0.tgz";
        sha1 = "7344cbb8b6e26fb27d66b2fc86f9f6d5997521c6";
      };
    };
    "slimscroll-0.9.1" = {
      name = "slimscroll";
      packageName = "slimscroll";
      version = "0.9.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/slimscroll/-/slimscroll-0.9.1.tgz";
        sha1 = "f675cdc601d80ada20f16004d227d156fd1187b2";
      };
    };
    "source-map-0.5.7" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.5.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.5.7.tgz";
        sha1 = "8a039d2d1021d22d1ea14c80d8ea468ba2ef3fcc";
      };
    };
    "stream-browserify-2.0.2" = {
      name = "stream-browserify";
      packageName = "stream-browserify";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/stream-browserify/-/stream-browserify-2.0.2.tgz";
        sha512 = "nX6hmklHs/gr2FuxYDltq8fJA1GDlxKQCz8O/IM4atRqBH8OORmBNgfvW5gG10GT/qQ9u0CzIvr2X5Pkt6ntqg==";
      };
    };
    "stream-combiner2-1.1.1" = {
      name = "stream-combiner2";
      packageName = "stream-combiner2";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/stream-combiner2/-/stream-combiner2-1.1.1.tgz";
        sha1 = "fb4d8a1420ea362764e21ad4780397bebcb41cbe";
      };
    };
    "stream-http-3.1.0" = {
      name = "stream-http";
      packageName = "stream-http";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/stream-http/-/stream-http-3.1.0.tgz";
        sha512 = "cuB6RgO7BqC4FBYzmnvhob5Do3wIdIsXAgGycHJnW+981gHqoYcYz9lqjJrk8WXRddbwPuqPYRl+bag6mYv4lw==";
      };
    };
    "stream-splicer-2.0.1" = {
      name = "stream-splicer";
      packageName = "stream-splicer";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/stream-splicer/-/stream-splicer-2.0.1.tgz";
        sha512 = "Xizh4/NPuYSyAXyT7g8IvdJ9HJpxIGL9PjyhtywCZvvP0OPIdqyrr4dMikeuvY8xahpdKEBlBTySe583totajg==";
      };
    };
    "string_decoder-1.1.1" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/string_decoder/-/string_decoder-1.1.1.tgz";
        sha512 = "n/ShnvDi6FHbbVfviro+WojiFzv+s8MPMHBczVePfUpDJLwoLT0ht1l4YwBCbi8pJAveEEdnkHyPyTP/mzRfwg==";
      };
    };
    "subarg-1.0.0" = {
      name = "subarg";
      packageName = "subarg";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/subarg/-/subarg-1.0.0.tgz";
        sha1 = "f62cf17581e996b48fc965699f54c06ae268b8d2";
      };
    };
    "sweetalert-0.4.2" = {
      name = "sweetalert";
      packageName = "sweetalert";
      version = "0.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/sweetalert/-/sweetalert-0.4.2.tgz";
        sha1 = "fc09ef88948d0f25e4f1232a22149f09e703753e";
      };
    };
    "sweetalert-1.1.3" = {
      name = "sweetalert";
      packageName = "sweetalert";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/sweetalert/-/sweetalert-1.1.3.tgz";
        sha1 = "d2c31ea492b22b6a8d887aea15989a238fc084ae";
      };
    };
    "syntax-error-1.4.0" = {
      name = "syntax-error";
      packageName = "syntax-error";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/syntax-error/-/syntax-error-1.4.0.tgz";
        sha512 = "YPPlu67mdnHGTup2A8ff7BC2Pjq0e0Yp/IyTFN03zWO0RcK07uLcbi7C2KpGR2FvWbaB0+bfE27a+sBKebSo7w==";
      };
    };
    "through-2.3.8" = {
      name = "through";
      packageName = "through";
      version = "2.3.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/through/-/through-2.3.8.tgz";
        sha1 = "0dd4c9ffaabc357960b1b724115d7e0e86a2e1f5";
      };
    };
    "through2-2.0.3" = {
      name = "through2";
      packageName = "through2";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/through2/-/through2-2.0.3.tgz";
        sha1 = "0004569b37c7c74ba39c43f3ced78d1ad94140be";
      };
    };
    "ticky-1.0.1" = {
      name = "ticky";
      packageName = "ticky";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ticky/-/ticky-1.0.1.tgz";
        sha1 = "b7cfa71e768f1c9000c497b9151b30947c50e46d";
      };
    };
    "timers-browserify-1.4.2" = {
      name = "timers-browserify";
      packageName = "timers-browserify";
      version = "1.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/timers-browserify/-/timers-browserify-1.4.2.tgz";
        sha1 = "c9c58b575be8407375cb5e2462dacee74359f41d";
      };
    };
    "tty-browserify-0.0.1" = {
      name = "tty-browserify";
      packageName = "tty-browserify";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/tty-browserify/-/tty-browserify-0.0.1.tgz";
        sha512 = "C3TaO7K81YvjCgQH9Q1S3R3P3BtN3RIM8n+OvX4il1K1zgE8ZhI0op7kClgkxtutIE8hQrcrHBXvIheqKUUCxw==";
      };
    };
    "typedarray-0.0.6" = {
      name = "typedarray";
      packageName = "typedarray";
      version = "0.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/typedarray/-/typedarray-0.0.6.tgz";
        sha1 = "867ac74e3864187b1d3d47d996a78ec5c8830777";
      };
    };
    "ultron-1.0.2" = {
      name = "ultron";
      packageName = "ultron";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ultron/-/ultron-1.0.2.tgz";
        sha1 = "ace116ab557cd197386a4e88f4685378c8b2e4fa";
      };
    };
    "umd-3.0.3" = {
      name = "umd";
      packageName = "umd";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/umd/-/umd-3.0.3.tgz";
        sha512 = "4IcGSufhFshvLNcMCV80UnQVlZ5pMOC8mvNPForqwA4+lzYQuetTESLDQkeLmihq8bRcnpbQa48Wb8Lh16/xow==";
      };
    };
    "undeclared-identifiers-1.1.3" = {
      name = "undeclared-identifiers";
      packageName = "undeclared-identifiers";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/undeclared-identifiers/-/undeclared-identifiers-1.1.3.tgz";
        sha512 = "pJOW4nxjlmfwKApE4zvxLScM/njmwj/DiUBv7EabwE4O8kRUy+HIwxQtZLBPll/jx1LJyBcqNfB3/cpv9EZwOw==";
      };
    };
    "url-0.11.0" = {
      name = "url";
      packageName = "url";
      version = "0.11.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/url/-/url-0.11.0.tgz";
        sha1 = "3838e97cfc60521eb73c525a8e55bfdd9e2e28f1";
      };
    };
    "util-0.10.3" = {
      name = "util";
      packageName = "util";
      version = "0.10.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/util/-/util-0.10.3.tgz";
        sha1 = "7afb1afe50805246489e3db7fe0ed379336ac0f9";
      };
    };
    "util-0.10.4" = {
      name = "util";
      packageName = "util";
      version = "0.10.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/util/-/util-0.10.4.tgz";
        sha512 = "0Pm9hTQ3se5ll1XihRic3FDIku70C+iHUdT/W926rSgHV5QgXsYbKZN8MSC3tJtSkhuROzvsQjAaFENRXr+19A==";
      };
    };
    "util-deprecate-1.0.2" = {
      name = "util-deprecate";
      packageName = "util-deprecate";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/util-deprecate/-/util-deprecate-1.0.2.tgz";
        sha1 = "450d4dc9fa70de732762fbd2d4a28981419a0ccf";
      };
    };
    "util-extend-1.0.3" = {
      name = "util-extend";
      packageName = "util-extend";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/util-extend/-/util-extend-1.0.3.tgz";
        sha1 = "a7c216d267545169637b3b6edc6ca9119e2ff93f";
      };
    };
    "vm-browserify-1.1.2" = {
      name = "vm-browserify";
      packageName = "vm-browserify";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/vm-browserify/-/vm-browserify-1.1.2.tgz";
        sha512 = "2ham8XPWTONajOR0ohOKOHXkm3+gaBmGut3SRuu75xLd/RRaY6vqgh8NBYYk7+RW3u5AtzPQZG8F10LHkl0lAQ==";
      };
    };
    "wrappy-1.0.2" = {
      name = "wrappy";
      packageName = "wrappy";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz";
        sha1 = "b5243d8f3ec1aa35f1364605bc0d1036e30ab69f";
      };
    };
    "ws-1.1.5" = {
      name = "ws";
      packageName = "ws";
      version = "1.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/ws/-/ws-1.1.5.tgz";
        sha512 = "o3KqipXNUdS7wpQzBHSe180lBGO60SoK0yVo3CYJgb2MkobuWuBX6dhkYP5ORCLd55y+SaflMOV5fqAB53ux4w==";
      };
    };
    "xtend-4.0.1" = {
      name = "xtend";
      packageName = "xtend";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/xtend/-/xtend-4.0.1.tgz";
        sha1 = "a5c6d532be656e23db820efb943a1f04998d63af";
      };
    };
    "xtend-4.0.2" = {
      name = "xtend";
      packageName = "xtend";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/xtend/-/xtend-4.0.2.tgz";
        sha512 = "LKYU1iAXJXUgAXn9URjiu+MWhyUXHsvfp7mcuYm9dSUKK0/CjtrUwFAxD82/mCWbtLsGjFIad0wIsod4zrTAEQ==";
      };
    };
    "zrender-3.7.4" = {
      name = "zrender";
      packageName = "zrender";
      version = "3.7.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/zrender/-/zrender-3.7.4.tgz";
        sha512 = "5Nz7+L1wIoL0+Pp/iOP56jD6eD017qC9VRSgUBheXBiAHgOBJZ4uh4/g6e83acIwa8RKSyZf/FlceKu5ntUuxQ==";
      };
    };
  };
  args = {
    name = "ariang";
    packageName = "ariang";
    version = "1.2.2";
    src = ./.;
    dependencies = [
      sources."JSONStream-1.3.5"
      (sources."acorn-node-1.8.2" // {
        dependencies = [
          sources."acorn-7.1.1"
          sources."xtend-4.0.2"
        ];
      })
      sources."acorn-walk-7.1.1"
      sources."admin-lte-2.4.18"
      sources."angular-1.6.10"
      sources."angular-animate-1.6.10"
      sources."angular-bittorrent-peerid-1.3.2"
      sources."angular-busy-4.1.4"
      sources."angular-clipboard-1.7.0"
      sources."angular-cookies-1.6.10"
      sources."angular-input-dropdown-git://github.com/mayswind/angular-input-dropdown.git#68670e39816698b3eb98c0e740a0efe77d5fbdd1"
      sources."angular-local-storage-0.7.1"
      sources."angular-messages-1.6.10"
      sources."angular-moment-1.3.0"
      (sources."angular-promise-buttons-0.1.23" // {
        dependencies = [
          sources."angular-1.7.0"
        ];
      })
      sources."angular-route-1.6.10"
      sources."angular-sanitize-1.6.10"
      (sources."angular-sweetalert-1.1.2" // {
        dependencies = [
          sources."sweetalert-0.4.2"
        ];
      })
      sources."angular-touch-1.6.10"
      (sources."angular-translate-2.18.4" // {
        dependencies = [
          sources."angular-1.8.2"
        ];
      })
      sources."angular-ui-notification-0.3.6"
      sources."angular-utf8-base64-0.0.5"
      sources."angular-websocket-2.0.1"
      sources."angularjs-dragula-2.0.0"
      sources."asn1.js-4.10.1"
      (sources."assert-1.5.0" // {
        dependencies = [
          sources."inherits-2.0.1"
          sources."util-0.10.3"
        ];
      })
      sources."atoa-1.0.0"
      sources."awesome-bootstrap-checkbox-0.3.7"
      sources."balanced-match-1.0.0"
      sources."base64-js-1.3.1"
      sources."bn.js-4.11.8"
      sources."bootstrap-3.4.1"
      sources."bootstrap-colorpicker-2.5.3"
      sources."bootstrap-contextmenu-1.0.0"
      sources."bootstrap-datepicker-1.9.0"
      sources."bootstrap-daterangepicker-2.1.30"
      sources."bootstrap-slider-9.10.0"
      sources."brace-expansion-1.1.11"
      sources."brorand-1.1.0"
      sources."browser-pack-6.1.0"
      (sources."browser-resolve-1.11.3" // {
        dependencies = [
          sources."resolve-1.1.7"
        ];
      })
      sources."browserify-16.5.1"
      sources."browserify-aes-1.2.0"
      sources."browserify-cipher-1.0.1"
      sources."browserify-des-1.0.2"
      sources."browserify-rsa-4.0.1"
      sources."browserify-sign-4.0.4"
      sources."browserify-zlib-0.2.0"
      sources."buffer-5.2.1"
      sources."buffer-from-1.1.1"
      sources."buffer-xor-1.0.3"
      sources."builtin-status-codes-3.0.0"
      sources."cached-path-relative-1.0.2"
      sources."charm-0.1.2"
      sources."chart.js-1.1.1"
      sources."cipher-base-1.0.4"
      sources."ckeditor-4.12.1"
      sources."classie-1.0.0"
      sources."combine-source-map-0.8.0"
      sources."concat-map-0.0.1"
      sources."concat-stream-1.6.2"
      sources."console-browserify-1.2.0"
      sources."constants-browserify-1.0.0"
      sources."contra-1.9.4"
      sources."convert-source-map-1.1.3"
      sources."core-util-is-1.0.2"
      sources."create-ecdh-4.0.3"
      sources."create-hash-1.2.0"
      sources."create-hmac-1.1.7"
      sources."crossvent-1.5.4"
      sources."crypto-browserify-3.12.0"
      sources."custom-event-1.0.0"
      sources."dash-ast-1.0.0"
      sources."datatables.net-1.10.20"
      sources."datatables.net-bs-1.10.20"
      sources."defined-1.0.0"
      sources."deps-sort-2.0.1"
      sources."des.js-1.0.1"
      sources."detective-5.2.0"
      sources."diffie-hellman-5.0.3"
      sources."domain-browser-1.2.0"
      sources."domhelper-0.9.1"
      sources."dragula-3.7.2"
      sources."duplexer2-0.1.4"
      sources."echarts-3.8.5"
      sources."elliptic-6.5.2"
      sources."eve-raphael-0.5.0"
      sources."events-2.1.0"
      sources."evp_bytestokey-1.0.3"
      sources."fast-safe-stringify-2.0.7"
      sources."fastclick-1.0.6"
      sources."flot-0.8.3"
      sources."font-awesome-4.7.0"
      sources."fs.realpath-1.0.0"
      sources."fullcalendar-3.10.1"
      sources."function-bind-1.1.1"
      sources."get-assigned-identifiers-1.2.0"
      sources."glob-7.1.2"
      sources."has-1.0.3"
      sources."hash-base-3.0.4"
      sources."hash.js-1.1.7"
      sources."hmac-drbg-1.0.1"
      sources."htmlescape-1.1.1"
      sources."https-browserify-1.0.0"
      sources."ieee754-1.1.13"
      sources."inflight-1.0.6"
      sources."inherits-2.0.3"
      sources."inline-source-map-0.6.2"
      sources."inputmask-3.3.11"
      sources."insert-module-globals-7.2.0"
      sources."ion-rangeslider-2.3.1"
      sources."ionicons-3.0.0"
      sources."is-buffer-1.1.6"
      sources."isarray-1.0.0"
      sources."jquery-3.4.1"
      sources."jquery-knob-1.2.11"
      sources."jquery-slimscroll-1.3.8"
      sources."jquery-sparkline-2.4.0"
      sources."jquery-ui-1.12.1"
      sources."json-stable-stringify-0.0.1"
      sources."jsonify-0.0.0"
      sources."jsonparse-1.3.1"
      sources."jvectormap-1.2.2"
      sources."labeled-stream-splicer-2.0.2"
      sources."lodash.memoize-3.0.4"
      sources."md5.js-1.3.5"
      sources."miller-rabin-4.0.1"
      sources."minimalistic-assert-1.0.1"
      sources."minimalistic-crypto-utils-1.0.1"
      sources."minimatch-3.0.4"
      sources."minimist-1.2.0"
      sources."mkdirp-classic-0.5.2"
      sources."module-deps-6.2.2"
      sources."moment-2.24.0"
      sources."moment-timezone-0.5.28"
      sources."morris.js-0.5.0"
      sources."natural-compare-1.4.0"
      sources."object-assign-4.1.1"
      sources."once-1.4.0"
      sources."options-0.0.6"
      sources."os-browserify-0.3.0"
      sources."pace-0.0.4"
      sources."pako-1.0.11"
      sources."parents-1.0.1"
      sources."parse-asn1-5.1.5"
      sources."path-browserify-0.0.1"
      sources."path-is-absolute-1.0.1"
      sources."path-parse-1.0.6"
      sources."path-platform-0.11.15"
      sources."pbkdf2-3.0.17"
      sources."process-0.11.10"
      sources."process-nextick-args-2.0.0"
      sources."public-encrypt-4.0.3"
      sources."punycode-1.4.1"
      sources."querystring-0.2.0"
      sources."querystring-es3-0.2.1"
      sources."randombytes-2.1.0"
      sources."randomfill-1.0.4"
      sources."raphael-2.3.0"
      sources."read-only-stream-2.0.0"
      sources."readable-stream-2.3.6"
      sources."resolve-1.8.1"
      sources."ripemd160-2.0.2"
      sources."safe-buffer-5.1.2"
      sources."select2-4.0.13"
      sources."sha.js-2.4.11"
      sources."shasum-1.0.2"
      sources."shasum-object-1.0.0"
      sources."shell-quote-1.7.2"
      sources."simple-concat-1.0.0"
      sources."slimscroll-0.9.1"
      sources."source-map-0.5.7"
      sources."stream-browserify-2.0.2"
      sources."stream-combiner2-1.1.1"
      (sources."stream-http-3.1.0" // {
        dependencies = [
          sources."readable-stream-3.6.0"
        ];
      })
      sources."stream-splicer-2.0.1"
      sources."string_decoder-1.1.1"
      sources."subarg-1.0.0"
      sources."sweetalert-1.1.3"
      sources."syntax-error-1.4.0"
      sources."through-2.3.8"
      sources."through2-2.0.3"
      sources."ticky-1.0.1"
      sources."timers-browserify-1.4.2"
      sources."tty-browserify-0.0.1"
      sources."typedarray-0.0.6"
      sources."ultron-1.0.2"
      sources."umd-3.0.3"
      sources."undeclared-identifiers-1.1.3"
      (sources."url-0.11.0" // {
        dependencies = [
          sources."punycode-1.3.2"
        ];
      })
      sources."util-0.10.4"
      sources."util-deprecate-1.0.2"
      sources."util-extend-1.0.3"
      sources."vm-browserify-1.1.2"
      sources."wrappy-1.0.2"
      sources."ws-1.1.5"
      sources."xtend-4.0.1"
      sources."zrender-3.7.4"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "AriaNg, a modern web frontend making aria2 easier to use.";
      homepage = "http://ariang.mayswind.net/";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = false;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (lib.overrideExisting args {
    src = stdenv.mkDerivation {
      name = args.name + "-package-json";
      src = nix-gitignore.gitignoreSourcePure [
        "*"
        "!package.json"
        "!package-lock.json"
      ] args.src;
      dontBuild = true;
      installPhase = "mkdir -p $out; cp -r ./* $out;";
    };
  });
}
